version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"           # Mapea el puerto 3000 del contenedor al host
    environment:
      - CHOKIDAR_USEPOLLING=true # Soluciona problemas de hot reload en Docker
    volumes:
      - .:/app                # Monta el directorio actual dentro del contenedor
      - node_modules:/app/node_modules # Usa un volumen nombrado para evitar conflictos
    stdin_open: true          # Habilita la terminal interactiva (opcional)
    tty: true                 # Asigna un TTY para depuración (opcional)

volumes:
  node_modules:
